- name: Generic Server Fixes
  hosts: web_servers
  become: yes

  tasks:
    - name: Disable SELinux
      become_method: sudo
      become_user: root
      selinux:
        state: disabled
    
    - name: Change default workers in nginx
      become_user: root
      become_method: sudo
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^worker_processes'
        line: 'worker_processes 4028;'

    - name: Change upload limit on nginx
      become_user: root
      become_method: sudo
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^client_max_body_size'
        line: 'client_max_body_size 1000m;'

    - name: Update nginx service section
      become_user: root
      become_method: sudo
      lineinfile:
        path: /usr/lib/systemd/system/nginx.service
        regexp: '^LimitNOFILE'
        line: 'LimitNOFILE=16384'
