- hosts: all
  gather_facts: true
  become_user: root
  become_method: sudo
  vars_prompt: |
    - name: confirm
      prompt: >-
        You have selected {{ ansible_play_batch }}. Do you want
        to continue?
    - name: zabbix_server_ip_hostname
      prompt: "What is the IP address or hostname of the Zabbix server or Proxy this agent should connect to?"
      private: no
      default: ""

  tasks:
    - name: Check for confirmation
      failed_when: confirm.lower() != 'y'
      ansible.builtin.command: /bin/true

    # DEPLOY THE AGENT
    - name: Set Facts for Agent Deployment
      set_fact:
        the_hostname: "{{ ansible_hostname }}"
        zabbix_release_rpm: "https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-release-5.4-1.el7.noarch.rpm"

    - name: Install Zabbix Release RPM
      become: True
      yum:
        name: "{{ zabbix_release_rpm }}"
        state: present

    - name: Install Zabbix Agent 2
      become: True
      yum:
        name: zabbix-agent2
        state: latest

    - name: Deploy Zabbix Pre-shared Key
      become: True
      template:
        src: "global_templates/zabbix/shared/zabbix.psk"
        dest: "/etc/zabbix/zabbix.psk"

    - name: Deploy Zabbix Agent 2 Configuration
      become: True
      template:
        src: "global_templates/zabbix/agent2/zabbix_agent2.conf.j2"
        dest: "/etc/zabbix/zabbix_agent2.conf"

    - name: Add Zabbix User to Docker Group
      become: True
      user:
        name: 'zabbix'
        groups: docker
        append: yes

    - name: Enable and Start Zabbix Agent 2
      become: True
      service:
        name: zabbix-agent2
        state: restarted
        enabled: yes
